# Generated by Django 4.0.3 on 2022-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_book',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='recipe_link',
            field=models.URLField(default='N/A'),
            preserve_default=False,
        ),
    ]
