# Generated by Django 4.0.3 on 2022-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_recipe_book_post_recipe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipe_book',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe_link',
            field=models.URLField(blank=True),
        ),
    ]
