# Generated by Django 4.0.3 on 2022-04-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_recipe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recipe_book',
        ),
        migrations.RemoveField(
            model_name='post',
            name='recipe_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='recipe_type',
        ),
    ]
