# Generated by Django 4.0.3 on 2022-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_recipe_book_remove_post_recipe_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_book',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='recipe_link',
            field=models.URLField(blank=True),
        ),
    ]
