# Generated by Django 4.2 on 2023-04-12 02:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0007_post_recipe_book_post_recipe_link"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Recipe",
        ),
    ]
